// This project has no license.
// Created on: 21-04-2021
package mealplanner.views;

import javax.swing.AbstractListModel;

/**
 *
 * @author johnholtzworth
 */
public class ListView extends javax.swing.JPanel {

    public final String title;
    private AbstractListModel<String> contents;

    public ListViewDataSource dataSource;
    public ListViewDelegate delegate;

    /**
     * Creates new form FoodListView
     *
     * @param title The title of the list view.
     */
    public ListView(String title) {
        this.title = title;
        ListView self = this;

        contents = new AbstractListModel<String>() {
            @Override
            public int getSize() {
                if (dataSource != null) {
                    return dataSource.numberOfRows(self);
                }
                return 0;
            }

            @Override
            public String getElementAt(int i) {
                if (dataSource != null) {
                    return dataSource.contentsOfRow(self, i);
                }
                return "Element " + i;
            }
        };

        initComponents();
    }

    public void deselect() {
        list.clearSelection();
    }

    public void reloadData() {
        ListView self = this;
        deselect();

        contents = new AbstractListModel<String>() {
            @Override
            public int getSize() {
                if (dataSource != null) {
                    return dataSource.numberOfRows(self);
                }
                return 0;
            }

            @Override
            public String getElementAt(int i) {
                if (dataSource != null) {
                    return dataSource.contentsOfRow(self, i);
                }
                return "Element " + i;
            }
        };

        list.setModel(contents);
        list.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 440, 300));
        setMaximumSize(new java.awt.Dimension(460, 400));
        setMinimumSize(new java.awt.Dimension(460, 400));
        setPreferredSize(new java.awt.Dimension(460, 400));

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText(title);
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        list.setModel(contents);
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        scrollPanel.setViewportView(list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(scrollPanel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
        if (evt.getValueIsAdjusting() == false) {
            if (delegate != null) {
                int index = list.getSelectedIndex();
                if (index != -1) {
                    delegate.didSelectRow(this, index);
                }
            }
        }
    }//GEN-LAST:event_listValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> list;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
