// This project has no license.
package mealplanner.views;

/**
 *
 * @author Matthew
 */
public class RecipeInformationView extends javax.swing.JPanel {

    /**
     * Creates new form RecipeInformationView
     */
    public RecipeInformationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recipeNameLabel = new javax.swing.JLabel();
        recipeCategoryLabel = new javax.swing.JLabel();
        recipeInstructionLabel = new javax.swing.JLabel();
        recipeInstructionScroll = new javax.swing.JScrollPane();
        recipeInstructionText = new javax.swing.JTextArea();
        recipeNameScroll = new javax.swing.JScrollPane();
        recipeNameText = new javax.swing.JTextArea();
        ingredientsLabel = new javax.swing.JLabel();
        ingredientsScroll = new javax.swing.JScrollPane();
        ingredientsList = new javax.swing.JList<>();
        recipeCategory = new java.awt.Choice();

        setMaximumSize(new java.awt.Dimension(460, 680));
        setMinimumSize(new java.awt.Dimension(460, 680));

        recipeNameLabel.setText("Recipe Name:");

        recipeCategoryLabel.setText("Recipe Category:");

        recipeInstructionLabel.setText("Recipe Instructions:");

        recipeInstructionText.setColumns(20);
        recipeInstructionText.setRows(5);
        recipeInstructionText.setText("Instructions");
        recipeInstructionScroll.setViewportView(recipeInstructionText);

        recipeNameText.setColumns(20);
        recipeNameText.setRows(5);
        recipeNameText.setText("Name");
        recipeNameScroll.setViewportView(recipeNameText);

        ingredientsLabel.setText("Ingredients:");

        ingredientsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ingredientsScroll.setViewportView(ingredientsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ingredientsLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(recipeInstructionLabel)
                        .addComponent(recipeNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(recipeCategoryLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recipeInstructionScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(recipeNameScroll)
                    .addComponent(ingredientsScroll)
                    .addComponent(recipeCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recipeNameScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(recipeNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recipeCategoryLabel)
                    .addComponent(recipeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recipeInstructionLabel)
                    .addComponent(recipeInstructionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingredientsLabel)
                    .addComponent(ingredientsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ingredientsLabel;
    private javax.swing.JList<String> ingredientsList;
    private javax.swing.JScrollPane ingredientsScroll;
    private java.awt.Choice recipeCategory;
    private javax.swing.JLabel recipeCategoryLabel;
    private javax.swing.JLabel recipeInstructionLabel;
    private javax.swing.JScrollPane recipeInstructionScroll;
    private javax.swing.JTextArea recipeInstructionText;
    private javax.swing.JLabel recipeNameLabel;
    private javax.swing.JScrollPane recipeNameScroll;
    private javax.swing.JTextArea recipeNameText;
    // End of variables declaration//GEN-END:variables
}
