// This project has no license.
package mealplanner.views;
import javax.swing.JOptionPane;

/**
 *
 * @author Matthew
 */
public class RecipeIngredientAddView extends javax.swing.JPanel {

    /**
     * Creates new form RecipeIngredientAddView
     */
    public RecipeIngredientAddView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountLabel = new javax.swing.JLabel();
        ingredientAmountBox = new javax.swing.JSpinner();

        setMaximumSize(new java.awt.Dimension(460, 680));
        setMinimumSize(new java.awt.Dimension(460, 680));

        amountLabel.setText("Amount(Number)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ingredientAmountBox)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(amountLabel)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(amountLabel)
                .addGap(18, 18, 18)
                .addComponent(ingredientAmountBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public int getQuantity(){
        try {
            return (Integer) (ingredientAmountBox.getValue());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Amount must be a number", "InfoBox: Amount Error", JOptionPane.INFORMATION_MESSAGE);
            return -1;
        }
    }
    
    public void setQuantity(){
        ingredientAmountBox.setValue(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JSpinner ingredientAmountBox;
    // End of variables declaration//GEN-END:variables
}
