name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
            
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          
      - name: Create Secrets.java template
        run: 
          echo "package mealplanner;
          public class Secrets {
          public static final String USERNAME = \"<username>\";
          public static final String PASSWORD = \"<password>\";
          public static final String JDBCDRIVER = \"oracle.jdbc.driver.OracleDriver\";
          public static final String JDBCURL = \"jdbc:oracle:thin:@<ip_address>:<port>:<database>\";
          }" > MealPlanner/src/mealplanner/Secrets.java
          
      - name: Build and Test with Ant
        run: ant -noinput -buildfile MealPlanner/build.xml
